spring:
  # 环境 dev:开发环境|prod:生产环境
  profiles:
    active: prod # 激活的配置文件
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

server:
  max-http-header-size: 102400
  port: 8001

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI4G3YDVKD453rLQRPeAQj # 访问身份验证中用到用户标识
    access-key-secret: zHDmPtPZ6lzTfHWIuMnxdrYvEcSkHM # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucket-name: pyyybf # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    max-size: 10 # 上传文件大小限制(M)
    prefix: http://pyyybf.oss-cn-shanghai.aliyuncs.com/
    directory:
      root: judgmentDoc/
      avatars: avatars/

model:
  name: model
  url: http://172.29.7.224:8000/api/model

# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
ribbon:
  # 建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 10000
  # 建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 20000