spring:
  #?? dev:????|prod:????
  profiles:
    active: dev #???????
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

server:
  max-http-header-size: 102400
  port: 8001

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true