spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JudgmentDoc?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: root