spring:
  datasource:
    url: jdbc:mysql://106.15.121.37:3306/JudgmentDoc?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 123456

directory:
  static:
    fonts:
      simsun: /home/panyue/judgmentdoc/backend/src/main/resources/static/fonts/simsun.ttc,1
  temporary: /home/panyue/judgmentdoc/backend/src/main/resources/temporary/